### ISSUE TITLE
table设计

### ISSUE THREAD

**Issue by suoutsky** [suoutsky/three-body-problem#84]
# table的一些显示效果及技巧
![image](https://user-images.githubusercontent.com/12389235/50389629-75bf2d80-0767-11e9-836a-09545f83226a.png)

![image](https://user-images.githubusercontent.com/12389235/50389655-b3bc5180-0767-11e9-983d-2abb75ccfda4.png)

![image](https://user-images.githubusercontent.com/12389235/50389760-0e09e200-0769-11e9-9877-c1a4c8b4979a.png)

#  table的一些显示体验效果
1. 数字靠右，文字靠左。
2. 最大列宽

   > 3个关键值
   1. title 值
   2. 内容最长值
   3. 规定最长值

   > 计算
   1.  最长值为title时，取title。
   2. 最长值是内容时，看是否超出规定最长值，如果超过就取`规定值`,否则取内容最长值

```css
.table-cell {
        line-height:17px;
        padding-top: 6px;
        padding-bottom: 6px;
        cursor: pointer;
        word-wrap:
        break-word;
        text-overflow:ellipsis;
        white-space:nowrap;
        overflow:hidden;
        &:hover {
          white-space:normal;
          overflow:auto;
        }
      }
```
